version: '3.8'
services:
  pyapp:
    image: ergosteur/ytcommunity-to-webhook:latest
    build: .
    volumes:
      - ytctwh-data:/usr/src/app/data
    env_file:
      - stack.env

volumes:
  ytctwh-data:

